---
title: "R Notebook"
output: html_notebook
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analyse de l'effet du nombre de test sur le taux de sosification

```{r , echo=FALSE}
setwd("~/Documents/sosie-stand-alone/data/random_exp")
codec       <- read.csv("commons-codec-stmt.csv")
collections <- read.csv("commons-collections-stmt.csv")
io          <- read.csv("commons-io-stmt.csv")
lang        <- read.csv("commons-lang-stmt.csv")
gson        <- read.csv("gson-stmt.csv")
jgit        <- read.csv("jgit-stmt.csv")
donnees     <- rbind.data.frame(codec, collections, io, lang, gson, jgit)
donnees     <- donnees[donnees$nbCompile > 0 , ]
t_sosie <- donnees$nbSosie/donnees$nbCompile
```


```{r}

donnees3     <- donnees[donnees$nbCompile > 0 & donnees$nbTest > 0 , ]
t_sosie <- donnees3$nbSosie/donnees3$nbCompile
test_3 <- donnees3$nbTest

#test_3[(test_3 >= 2) & (test_3 < 4)] <- 2
#test_3[(test_3 >= 4) & (test_3 < 6)] <- 4
#test_3[(test_3 >= 6) & (test_3 < 9)] <- 6
#test_3[(test_3 >= 9) & (test_3 < 13)] <- 9
#test_3[(test_3 >= 13) & (test_3 < 24)] <- 13
#test_3[(test_3 >= 24) & (test_3 < 49)] <- 24
#test_3[(test_3 >= 49) & (test_3 < 167)] <- 49
#test_3[test_3 >= 167] <- 167

myformat <- function(data, breaks) {
  for( i in 2:length(breaks)) {
    data[(data >= breaks[i-1]) & (data < breaks[i])] <- breaks[i-1]
  }
  data[data >= breaks[length(breaks)]] <- breaks[length(breaks)]
  return(data)
}

#myBreaks <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,15,17,19,21,24,28,31,34,37,40,44,49,58,67,78,86,96,105,119,147,170, 198,232,268,327,351,465,489,490,759,1088)

myBreaks <- c(1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 17, 20, 23, 30, 35, 42, 51, 62, 82, 96, 118, 169, 232, 298, 422, 490, 922)
test_3 <- myformat(test_3, myBreaks)

moyenne <- c(0.2692218, 0.2617576, 0.2878822, 0.1911107, 0.2455951, 0.1449199, 0.2163342, 0.2531585, 0.3005165, 0.2487987, 0.1980918, 0.2526666, 0.2579648, 0.2589410, 0.2102249, 0.1872885, 0.2710396, 0.2240252, 0.3131804, 0.2084452, 0.3220220, 0.2710094, 0.1890017, 0.2043344, 0.1792312, 0.2304136, 0.1726108, 0.2115719)

#setEPS()
#postscript("sr-tc-all-var.eps")
boxplot(t_sosie~test_3, main = "", xlab = "Number of test cases", ylab = "Sosiefication rate", names = c("1", "2", "3", "4", "5", "6", "7", "8-9", "10-11", "12-13", "14-16", "17-19", "20-22", "23-29", "30-34", "35-41", "42-50", "51-61", "62-81", "82-95", "96-117", "118-168", "169-231", "232-297", "298-421", "422-489", "490-921", ">= 922"), las = 2)
lines(moyenne)
#dev.off()
```

