---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(matrixStats)
library(xtable)
```

# RQ1

## Data

```{r data, include=FALSE}
commons_codec_trials <- read_delim("../data/random_exp/commons-codec-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
commons_collections_trials <- read_delim("../data/random_exp/commons-collections-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
commons_io_trials <- read_delim("../data/random_exp/commons-io-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
commons_lang_trials <- read_delim("../data/random_exp/commons-lang-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
gson_trials <- read_delim("../data/random_exp/gson-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
jgit_trials <- read_delim("../data/random_exp/jgit-trials.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)
all_trials <- rbind(commons_codec_trials, commons_collections_trials, commons_io_trials, gson_trials, jgit_trials)

```

## Overall
```{r overall}
print_overview <- function(data, tname, pname) {
  
  all_success <- data %>% filter(status >= 0 & name==tname) %>% count_()
  all_compile <- data %>% filter(status >= -1 & name==tname) %>% count_()
  
  sr <- (all_success / all_compile) * 100
  return(c(
    all_success,
    all_compile,
    sr
  ))
}
print_total <- function(data, pname) {
  all_success <- data %>% filter(status >= 0) %>% count_()
  all_compile <- data %>% filter(status >= -1) %>% count_()
  sr <- (all_success / all_compile) * 100
  return(c(
    all_success,
    all_compile,
    sr
  ))
}

meta_print <- function(data, pname) {
  c(
    pname,
    print_overview(data, "add", pname),
    print_overview(data, "delete", pname),
    print_overview(data, "replace", pname),
    print_total(data, pname)
    )
}

overview <- rbind(
meta_print(commons_codec_trials, "commons-codec"),
meta_print(commons_collections_trials, "commons-collections"),
meta_print(commons_io_trials, "commons-io"),
meta_print(commons_lang_trials, "commons-lang"),
meta_print(gson_trials, "gson"),
meta_print(jgit_trials, "jgit"),
meta_print(all_trials, "total")
)
overview_df <- data.frame(matrix(unlist(overview), nrow=7, byrow=F))
names(overview_df) <- c("project", "add_success", "add_trial", "add_SR", "del_success", "del_trial", "del_SR", "rep_success", "rep_trial", "rep_SR", "total_success", "total_trial", "total_SR")
overview_df
```

```{r export}

table1 <- overview_df
table1$add_trial <- NULL
table1$del_trial <- NULL
table1$rep_trial <- NULL
table1$add_SR <- NULL
table1$del_SR <- NULL
table1$rep_SR <- NULL
table1$total_trial <- NULL
table1$total_success <- NULL

table2 <- overview_df
table2$add_trial <- NULL
table2$del_trial <- NULL
table2$rep_trial <- NULL
table2$add_success <- NULL
table2$del_success <- NULL
table2$rep_success <- NULL
table2$total_trial <- NULL
table2$total_success <- NULL
table2$total_SR <- NULL

xtable(table1)
xtable(table2)
```

